<h2><span style="color:red">🚨 Run the below cell to install and import required packages</span></h2>


In [2]:
!pip install numpy_assignment_tests-0.1-py3-none-any.whl --force-reinstall
import numpy as np

Processing c:\users\ashok\onedrive\desktop\ashoka\python_class_sure\18-04 classtest_numpy_operations\numpy_assignment_tests-0.1-py3-none-any.whl


## 📝 **18th April NumPy Class Test - 45 Minute Duration**

---

### ✅ **Problem 1: Array Creation and Basic Operations**

**Steps to solve:**

1. Create a NumPy array of even numbers from 10 to 50 (inclusive).
2. Multiply all elements of the array by 2 and store it in a new variable.
3. Compute the sum of all elements in the doubled array.
4. Reshape the doubled array into a 2D array with 5 rows and 4 columns.

**Function Signature:**

In [95]:
arr = np.arange(10, 50, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [96]:
arr_doubled = arr * 2
arr_doubled

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84,
       88, 92, 96])

In [97]:
total = np.sum(arr_doubled)
total

np.int64(1160)

In [98]:
reshaped = arr_doubled.reshape([5, 4]) 
reshaped

array([[20, 24, 28, 32],
       [36, 40, 44, 48],
       [52, 56, 60, 64],
       [68, 72, 76, 80],
       [84, 88, 92, 96]])

In [99]:
def problem1():
    a_np = np.arange(10, 50, 2)
    arr_doubled=a_np*2
    total=np.sum(arr_doubled)
    reshaped=arr_doubled.reshape(5,4)
    return arr_doubled, total, reshaped
print(problem1())

(array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84,
       88, 92, 96]), np.int64(1160), array([[20, 24, 28, 32],
       [36, 40, 44, 48],
       [52, 56, 60, 64],
       [68, 72, 76, 80],
       [84, 88, 92, 96]]))


In [100]:
try:
    from numpy_assignment_tests import test
    test.test_problem1(problem1)
except:
    print("Try Again!")

[✔] Problem 1 Passed — Score: 8/20



---

### ✅ **Problem 2: Indexing and Slicing**

**Steps to solve:**

1. Create a 5x5 NumPy array with numbers from 1 to 25 (row-wise).
2. Extract the 2nd and 4th rows (index 1 and 3).
3. Extract the 3rd column (index 2).
4. Extract a subarray from rows 2 to 4 and columns 2 to 5.

**Function Signature:**

In [26]:
arr = np.arange(1, 26).reshape(5, 5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
rows = arr[[1, 3]]
rows

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [31]:
col = arr[:, 2]
col

array([ 3,  8, 13, 18, 23])

In [30]:
subarray = arr[2:5, 2:5]
subarray

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [ ]:
def problem2():
    arr = np.arange(1, 26).reshape(5, 5)
    rows = arr[[1, 3]]
    col = arr[:, 2]
    subarray = arr[2:5, 2:5]
    return rows, col, subarray

In [33]:
try:
    from numpy_assignment_tests import test
    test.test_problem2(problem2)
except:
    print("Try Again!")

[✔] Problem 2 Passed — Score: 20/20


---

### ✅ **Problem 3: Boolean Masking and Conditional Operations**

**Steps to solve:**

1. Create a NumPy array of integers from 1 to 20.
2. Use boolean masking to extract all numbers divisible by 3.
3. Replace all numbers greater than 15 in the original array with -1.

**Function Signature:**

In [37]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
divisible_by_3 = arr[arr % 3 == 0]
divisible_by_3

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
replaced_array = arr.copy()
replaced_array[replaced_array > 15] = -1
replaced_array



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, -1, -1,
       -1, -1, -1])

In [48]:
def problem3():
    arr = np.arange(1, 21)
    divisible_by_3 = arr[arr % 3 == 0]
    replaced_array = arr.copy()
    replaced_array[replaced_array > 15] = -1
    return divisible_by_3, replaced_array
print(problem3())

(array([ 3,  6,  9, 12, 15, 18]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, -1, -1,
       -1, -1, -1]))


In [49]:
try:
    from numpy_assignment_tests import test
    test.test_problem3(problem3)
except:
    print("Try Again!")

[✔] Problem 3 Passed — Score: 20/20


---

### ✅ **Problem 4: Aggregate Functions and Axis Operations**

**Steps to solve:**

1. Create a 4x4 NumPy array with values from 1 to 16.
2. Calculate the mean of each row.
3. Calculate the sum of each column.

**Function Signature:**

In [50]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
row_means = np.mean(arr, axis=1) 
row_means

array([ 2.5,  6.5, 10.5, 14.5])

In [53]:
col_sums = np.sum(arr, axis=0)
col_sums

array([28, 32, 36, 40])

In [54]:
def problem4():
    arr = np.arange(1, 17).reshape(4, 4)
    row_means = np.mean(arr, axis=1)
    col_sums = np.sum(arr, axis=0)
    return row_means, col_sums
print(problem4())

(array([ 2.5,  6.5, 10.5, 14.5]), array([28, 32, 36, 40]))


In [55]:
try:
    from numpy_assignment_tests import test
    test.test_problem4(problem4)
except:
    print("Try Again!")

[✔] Problem 4 Passed — Score: 20/20


---

### ✅ **Problem 5: Stacking and Splitting Arrays**

**Steps to solve:**

1. Create two NumPy arrays: `a = [1, 2, 3]`, `b = [4, 5, 6]`.
2. Stack them vertically and horizontally.
3. Split the horizontal stacked array into two equal parts.

**Function Signature:**

In [57]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [62]:
vstacked = np.vstack((a, b))       
hstacked = np.hstack((a, b))  
vstacked, hstacked

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [ ]:
split_arrays = np.split(h_stack, 2) 
split_arrays


[array([1, 2, 3]), array([4, 5, 6])]

In [64]:
def problem5():
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    vstacked = np.vstack((a, b))       
    hstacked= np.hstack((a, b)) 
    split_arrays = np.split(hstacked, 2)
    return vstacked, hstacked, split_arrays
print(problem5())

(array([[1, 2, 3],
       [4, 5, 6]]), array([1, 2, 3, 4, 5, 6]), [array([1, 2, 3]), array([4, 5, 6])])


In [65]:
try:
    from numpy_assignment_tests import test
    test.test_problem5(problem5)
except:
    print("Try Again!")

[✔] Problem 5 Passed — Score: 20/20


<h3><span style="color:red">🚨 Run the below cell to execute all test cases and get the final score</span></h3>


In [67]:
## DO NOT MODIFY ##
try:
    from numpy_assignment_tests import test
    student_name = input("Enter your full name: ").strip()
    test.run_all_tests({
        "problem1": problem1,
        "problem2": problem2,
        "problem3": problem3,
        "problem4": problem4,
        "problem5": problem5
    }, student_name)
except:
    print("Check again and complete all the questions completely!!")

=== NumPy Assignment Evaluation ===
[✔] Problem 1 Passed — Score: 8/20
[✔] Problem 2 Passed — Score: 20/20
[✔] Problem 3 Passed — Score: 20/20
[✔] Problem 4 Passed — Score: 20/20
[✔] Problem 5 Passed — Score: 20/20

🏁 Final Score: 88/100
